# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15YYkxeN7apY56y51JUnFkHR6m4cKEIV8
"""

# Commented out IPython magic to ensure Python compatibility.
#  Ultralytics 설치
!pip install ultralytics --upgrade -q



#   작업 디렉토리 이동 (드라이브에 저장하고 싶으면 여기 변경 가능)
# %cd /content

#   데이터셋 업로드
from google.colab import files
uploaded = files.upload()  # keyboard_dataset.zip 올리기

# 압축 해제

!tar -xvf /content/keyboard_dataset.tar -C /content/
!ls /content/keyboard_dataset

#   파일 구조 확인
!ls keyboard_dataset

#   YOLO 모델 학습
from ultralytics import YOLO
model = YOLO('yolov8m.pt')  # 또는 yolov8x.pt

model.train(
    data='/content/keyboard_dataset/data.yaml',
    imgsz=960,
    epochs=100,
    batch=8,
    name='keyboard_detector_v2',
    box=10.0,
    mosaic=False,
    scale=0.3,
    hsv_h=0.005,
    hsv_s=0.2,
    hsv_v=0.2,
)

from google.colab import drive
drive.mount('/content/drive')